name: Build

on:
  pull_request:
    branches: ["main"]

jobs:
  build-front-end:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install deps
        working-directory: ./shop-angular-cloudfront
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: ./shop-angular-cloudfront
        run: yarn build
